<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class addactor extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('actor')->insert([
            ['name'=> 'Tom Hanks', 'slug' => Str::slug('Tom Hanks', '-'), 'birthday'=> '9 tháng 7, 1956 (64 tuổi)', 'nationality' => 'Concord, California, Hoa Kỳ', 'height' => '1m8', 'weight' => '70','story' => 'Hanks sinh ở thành phố Concord, California, Hoa Kỳ. Bố của ông, ông Amos Mefford Hanks là một đầu bếp, còn mẹ là Janet Marylyn Frager làm việc trong bệnh viện, hai người li dị nhau khi Hanks mới được 4 tuổi[2]. Tom Hanks có một người chị, Sandra Hanks (hiện là một nhà văn), một người anh Lawrence M. Hanks (nhà côn trùng học) và một người em trai Jim Hanks (cũng là diễn viên và nhà sản xuất phim).

            Ở trường học, Hanks ít được giáo viên và bạn bè chú ý và quý mến, ông đã kể với tạp chí Rolling Stone: "Khi còn là học sinh tôi rất lập dị và nhút nhát. Tuy vậy tôi lại là người có thể hét to những đoạn hội thoại buồn cười trong các bộ phim. Tôi chưa bao giờ gây ra rắc rối và luôn là một đứa trẻ ngoan, có trách nhiệm". Khi học cấp III ở trường Skyline, thành phố Oakland, California, Tom đã tham gia đóng những vở kịch của trường, trong đó có vở nhạc kịch South Pacific. Sau đó Hanks học về diễn xuất trong 2 năm ở trường cao đẳng Chabot trước khi chuyển đến Đại học của tiểu bang California tại Sacramento (California State University, Sacramento). Hanks đã trả lời phỏng vấn báo New York Times: "Các lớp học diễn xuất có lẽ là nơi tốt nhất cho những gã thích gây ồn ào và ưa khoa trương. Tôi đã dành rất nhiều thời gian để xem kịch. Tôi không bao giờ đi cùng ai mà cứ lái xe đến rạp, tự mua vé, ngồi vào ghế, đọc tờ chương trình và sau đó hoàn toàn nhập tâm vào vở kịch. Tôi xem rất nhiều, từ Bertolt Brecht, Tennessee Williams đến Henrik Ibsen và những người khác nữa."
            
            Trong thời gian học đại học, Hanks gặp Vincent Dowling, người phụ trách của liên hoan kịch Great Lakes Theater Festival ở Cleveland. Đồng ý với đề nghị của Dowling, Hanks trở thành người thực tập ở đây, trong 3 năm ông đã làm tất cả mọi việc từ phụ trách ánh sáng, dàn dựng đến quản lý sân khấu. Hợp đồng này buộc Hanks phải bỏ học nhưng nó lại mở ra tương lai diễn xuất cho ông. Hanks đã giành giải Nam diễn viên xuất sắc nhất của Hiệp hội phê bình Cleveland cho vai Proteus trong vở kịch của Shakespeare Hai quý ông thành Verona, đây cũng là một trong số ít lần Hanks vào vai phản diện.', 'image' => 'dv1.jpg'],
            ['name'=> 'Robert Downey Jr.', 'slug' => Str::slug('Robert Downey Jr.', '-'), 'birthday'=> '4 tháng 4, 1965 (55 tuổi)', 'nationality' => 'Thành phố New York, New York, Hoa Kỳ', 'height' => '1m8', 'weight' => '70', 'story' => 'Robert John Downey, Jr (sinh ngày 4 tháng 4 năm 1965) là một diễn viên người Mỹ. Ông sinh ra ở Thành phố New York, Hoa Kỳ. Ông diễn xuất từ khi mới 5 tuổi trong phim Pound của cha ông. Ông tham gia các phim như Less Than Zero, Air America, Natural Born Killers, Soapdish,... Gần đây là The Singing Detective, Kiss Kiss Bang Bang, A Scanner Darkly, Gothika, Zodiac, Tropic Thunder, Sherlock Holmes, Sherlock Holmes: Trò chơi của bóng đêm,... và đặc biệt là vai diễn chính Tony Stark / Iron Man trong 3 phần của loạt phim Iron Man được chuyển thể từ bộ truyện cùng tên của hãng Marvel Comics và trong các sản phẩm tương tự khác của hãng này (như The Incredible Hulk, The Avenger,...). Ông tham gia 3 series phim truyền hình là: Saturday Night Live, Ally McBeal và Family Guy.

            Downey được trao 2 Giải Quả Cầu Vàng cho Diễn viên chính xuất sắc nhất trong phim Short Cuts (1994) và Sherlock Holmes (2010), 1 giải Quả Cầu Vàng cho diễn viên phụ xuất sắc nhất trong series truyền hình Ally McBeal. Ông từng được đề cử trao Giải Oscar cho nam diễn viên chính xuất sắc nhất với vai diễn Charlie Chaplin trong phim Chaplin (1992).
            
            Downey đã tham gia 6 phim mà mỗi phim đều bán được không dưới 600 triệu USD tiền vé (4 trong số đó nằm trong danh sách những phim có doanh thu cao nhất của điện ảnh Hoa Kỳ, The Avengers, Avengers: Age of Ultron, Iron Man 3, Captain America: Civil War và Avengers: Endgame với doanh thu trên 1 tỉ USD mỗi phim), Ông đứng đầu trong danh sách những nam diễn viên có thu nhập cao nhất của tạp chí Forbes năm 2013 với tổng thu nhập ước tính trên 75 triệu USD chỉ riêng trong khoảng từ 6/2012 tới 6/2013.[1]', 'image' => 'dv2.jpg' ],
            ['name'=> 'Leonardo DiCaprio', 'slug' => Str::slug('Leonardo DiCaprio', '-'), 'birthday'=> '11 tháng 11, 1974 (46 tuổi)', 'nationality' => 'Hoa Kỳ', 'height' => '1m7', 'weight' => '66', 'story' => 'Leonardo Wilhelm DiCaprio sinh ngày 11 tháng 11 năm 1974 tại Los Angeles.[5] Anh là con một của bà Irmelin (née Indenbirken), một thư ký pháp luật, và ông George DiCaprio, một nghệ sĩ Underground comix và là nhà sản xuất và phân phối truyện tranh.[6] Cha của DiCaprio thuộc dòng dõi người Ý (từ Napoli) và người Đức (từ Bayern).[7][8][9] Ông ngoại của DiCaprio, Wilhelm Indenbirken, là người Đức.[10] Bà ngoại của ông, Helene Indenbirken (sinh ra ở Yelena Smirnova, 1915-2008),[11] là một người Nga gốc Đức.[12][13] Trong một cuộc phỏng vấn ở Nga, DiCaprio gọi mình là "một nửa Nga" và nói rằng hai ông bà của anh là người Nga.[14] Cha mẹ của DiCaprio đã gặp gỡ khi đang học đại học và sau đó chuyển đến Los Angeles, California.[7]

            DiCaprio được đặt tên là Leonardo bởi vì khi là thai nhi, lần đầu tiên anh đá bụng mẹ trong lúc bà đang nhìn bức tranh sơn dầu Leonardo da Vinci tại một viện bảo tàng ở Ý.[15] Cha mẹ anh ly thân khi anh mới 1 tuổi, và anh hầu như sống với mẹ.[16] Hai người sống tại một số vùng lân cận ở Los Angeles, như Echo Park và Los Feliz (nơi cư trú của ông ở Los Feliz sau đó được chuyển thành thư viện công cộng), trong khi mẹ anh làm nhiều công việc.[7] DiCaprio đã theo học tại trường tiểu học Seeds Elementary School (nay là trường tiểu học UCLA Lab School) và trường trung học John Marshall High School cách đó vài dãy nhà, sau khi theo học ở Los Angeles Center for Enriched Studies trong bốn năm.[17] Tuy nhiên, anh đã bỏ học trung học sau năm thứ ba, cuối cùng đạt được bằng tương đương với bằng tốt nghiệp phổ thông trung học (GED).[18][19] DiCaprio đã trải qua thời thơ ấu của mình ở Đức cùng với ông bà Wilhelm và Helene. Anh thông thạo tiếng Đức và tiếng Ý. [20][21][22]', 'image' => 'dv3.jpg'],
            ['name'=> 'Will Smith', 'slug' => Str::slug('Will Smith', '-'), 'birthday'=> '25 tháng 9, 1968 (52 tuổi)', 'nationality' => 'Mỹ', 'height' => '1m7', 'weight' => '45', 'story' => 'Willard Christopher "Will" Smith, Jr. (sinh ngày 25 tháng 9, năm 1968) là một diễn viên, rapper, nhà sản xuất và nhạc sĩ người Mỹ. Tháng 4 năm 2007, Newsweek đã xem xét ông là "nam diễn viên quyền lực nhất Hollywood". Smith đã được đề cử cho năm giải thưởng Quả Cầu Vàng (Golden Globe Awards) và hai giải thưởng của Viện Hàn lâm (Academy Awards), và đã giành được bốn giải Grammy.

            Vào cuối những năm 1980, ông chỉ nổi tiếng với công việc rapper nghệ danh là The Fresh Prince. Năm 1990, anh dần trở nên nổi tiếng sau khi đóng vai chính trong bộ phim truyền hình nổi tiếng NBC The Fresh Prince of Bel-Air, dài 6 mùa (đến năm 1996). Sau khi bộ phim kết thúc bộ phim, anh chuyển qua làm diễn viên điện ảnh và trở thành ngôi sao trong nhiều bộ phim bom tấn. Anh là diễn viên duy nhất có tám bộ phim liên tiếp thu về tổng cộng hơn 100 triệu đô la ở rạp chiếu phim trong nước, 11 bộ phim liên tiếp thu về trên 150 triệu đôla trên toàn thế giới, và tám bộ phim liên tiếp mà anh đóng vai chính ở vị trí số một tại doanh thu trong nước.
            
            Smith đã được tạp chí Forbes bình chọn là ngôi sao "bankable" (diễn viên có sức hút đến mức chỉ cần xuất hiện trong phim là đủ đảm bảo doanh thu phòng vé của bộ phim đó) nhất trên toàn thế giới. Tính đến năm 2014, 17 trong số 21 bộ phim mà anh đóng vai chính đã thu được tổng thu nhập trên 100 triệu đô la Mỹ trên toàn thế giới, mỗi năm thu về hơn 500 triệu đô la Mỹ. Tính đến năm 2016, bộ phim của ông đã thu về 7,5 tỷ đô la tại các phòng vé toàn cầu. Với vai diễn trong phim Ali (2001) và The Pursuit of Happiness (2006), Smith đã nhận được đề cử giải Oscar cho mục "Nam diễn viên xuất sắc nhất".', 'image' => 'dv4.jpg'],
            ['name'=> 'Tom Cruise', 'slug' => Str::slug('Tom Cruise', '-'), 'birthday'=> '3 tháng 7, 1962 (58 tuổi)', 'nationality' => 'Mỹ', 'height' => '1m7', 'weight' => '67', 'story' => 'Thomas Cruise Mapother IV (sinh ngày 3 tháng 7 năm 1962) là một nam diễn viên và nhà sản xuất người Mỹ. Anh bắt đầu sự nghiệp của mình ở tuổi 19 với bộ phim Endless Love, trước khi nhận được sự chú ý từ công chúng với vai diễn Trung úy Pete "Maverick" Mitchell trong Top Gun. Cruise cũng được biết đến rộng rãi với vai diễn điệp viên IMF Ethan Hunt trong loạt phim Nhiệm vụ bất khả thi. Anh đã giành chiến thắng một giải Quả cầu vàng ở hạng mục Nam diễn viên phim chính kịch xuất sắc nhất vào năm 1990 cho vai diễn trong bộ phim Born on the Fourth of July; Nam diễn viên phim ca nhạc hoặc phim hài xuất sắc nhất vào năm 1997 cho Jerry Maguire; và Nam diễn viên điện ảnh phụ xuất sắc nhất vào năm 2000 cho bộ phim Magnolia. Tính tới tháng 9 năm 2017, Các bộ phim có Cruise tham gia đã đạt mức doanh thu 3,7 tỉ USD tại phòng vé Mỹ và Canada, cũng như tổng 9,0 tỉ USD toàn cầu,[1] giúp anh trở thành nam diễn viên đạt doanh thu cao thứ tám ở Bắc Mỹ và đồng thời là một trong những nam diễn viên có doanh thu phim cao nhất toàn cầu.[2]

            Ngoài ra, Cruise còn là một người ủng hộ Giáo hội Khoa luận giáo và các chương trình xã hội liên quan, vì tôn giáo này đã giúp anh vượt qua chứng khó đọc.', 'image' => 'dv5.jpg'],
            ['name'=> 'Johnny Depp', 'slug' => Str::slug('Johnny Depp', '-'), 'birthday'=> '9 tháng 6, 1963 (57 tuổi)', 'nationality' => 'Mỹ', 'height' => '1m7', 'weight' => '77', 'story' => 'Depp sinh tại Owensboro, Kentucky, là con của Betty Sue, một bồi bàn, và John Christopher Depp Senior, một kĩ sư. Depp có một người anh em trai, Danny, và hai chị em gái, Christie (hiện tại đang là người quản lý của Depp) và Debbie. Depp mang dòng máu Đức, Cherokee, Ireland. Trong quyển Johnny Depp: Một ảo ảnh nêu rằng gia đình Depp có mối liên hệ với nhà truyền đạo Tin Lành người Pháp đã định cư ở Virginia vào khoảng những năm 1700. Depp nói anh không biết nguồn gốc tên họ của anh, nhưng nói đùa rằng nó có nghĩa "đồ ngốc" trong tiếng Đức.

            Gia đình Depp chuyển nhà thường xuyên khi anh còn nhỏ, và anh đã từng sống tại hơn hai mươi khu vực khác nhau ở Florida trong năm 1970, khi anh 7 tuổi. Năm 1978, 15 tuổi, cha mẹ anh li dị. Để thoát khỏi sự căng thẳng tâm lý do các vấn đề của gia đình và do sự thiếu tự tin, cậu bé Depp đã mắc phải hội chứng tự ngược đãi bản thân (self-harm). Việc đó đã để lại cho Depp bảy hay tám vết sẹo. Trong bài phỏng vấn năm 1993, Depp nói: "Cơ thể của tôi cũng như một quyển nhật ký vậy. Nó cũng giống như các hình xăm của một người thủy thủ, khi một sự kiện đặc biệt xảy ra trong đời anh và anh muốn đánh dấu nó trên chính cơ thể mình. Dù cho anh tự làm việc đó hay do một người nghệ sĩ xăm hình thực hiện cho anh."[1].', 'image' => 'dv6.jpg'],
            ['name'=> 'Scarlett Johansson', 'slug' => Str::slug('Scarlett Johansson', '-'), 'birthday'=> '22 tháng 11, 1984 (36 tuổi)', 'nationality' => 'Thành phố New York, Hoa Kỳ.', 'height' => '1m7', 'weight' => '88', 'story' => 'Scarlett Ingrid Johansson (/dʒoʊˈhænsən/; sinh ngày 22 tháng 11 năm 1984) là một nữ diễn viên và ca sĩ người Mỹ. Là nữ diễn viên được trả lương cao nhất thế giới kể từ năm 2018, cô đã nhiều lần xuất hiện trong danh sách 100 người nổi tiếng quyền lực nhất thế giới theo Forbes. Những bộ phim của cô đã thu về hơn 14,3 tỷ đô la trên toàn thế giới, đưa Johansson trở thành một trong những ngôi sao có doanh thu phòng vé cao nhất mọi thời đại. Cô cũng nhận được nhiều giải thưởng cao quý, bao gồm một giải Tony và một giải BAFTA, cũng như được đề cử cho hai giải Oscar và năm giải Quả cầu vàng.

            Sinh ra và lớn lên ở Manhattan, thành phố New York, Johansson khao khát trở thành một diễn viên từ khi còn nhỏ và lần đầu tiên xuất hiện trên sân khấu Off-Broadway với tư cách là một diễn viên nhí. Bộ phim đầu tay của cô là bộ phim hài giả tưởng North (1994), và sớm được công nhận với các vai diễn trong Manny & Lo (1996), The Horse Whisperer (1998) và Ghost World (2001). Johansson trưởng thành hơn với vai diễn của cô trong Lost in Translation, bộ phim đã mang về cho cô giải BAFTA cho Nữ diễn viên chính xuất sắc nhất cùng với Girl with a Pearl Earring. Cô cũng được đề cử giải Quả cầu vàng cho những bộ phim này, cô thủ vai một thiếu nữ bị ghẻ lạnh trong bộ phim truyền hình A Love Song for Bobby Long (2004) và một cô gái quyến rũ trong bộ phim kinh dị tâm lý Match Point (2005). Các bộ phim khác trong giai đoạn này bao gồm The Prestige (2006) và Vicky Cristina Barcelona (2008); các album Anywhere I Lay My Head (2008) và Break Up (2009), cả hai đều lọt vào bảng xếp hạng Billboard 200.', 'image' => 'dv7.jpg'],
            ['name'=> 'Natalie Portman', 'slug' => Str::slug('Natalie Portman', '-'), 'birthday'=> '9 tháng 6, 1981 (39 tuổi)', 'nationality' => 'Jerusalem, Israel', 'height' => '1m7', 'weight' => '45', 'story' => 'Natalie Portman (tiếng Hebrew: נטלי פורטמן, tên khai sinh: Natalie Hershlag, נטלי הרשלג), sinh ngày 9 tháng 6 năm 1981 tại Jerusalem, Israel). Cô là một nữ diễn viên người Mỹ gốc Israel từng đoạt 1 giải Oscar và 2 giải Quả Cầu Vàng.

            Vai diễn đầu tay của cô là trong bộ phim độc lập Léon. Trong khi vẫn còn học trung học, cô đã nổi tiếng toàn thế giới với vai diễn Padmé Amidala trong Star Wars: Tập I - The Phantom Menace và nhận được sự ca ngợi từ giới phê bình khi đóng vai một thiếu niên già trước tuổi trong bộ phim Anywhere but Here (1999). Từ năm 1999 đến năm 2003, Portman theo học Đại học Harvard để lấy bằng cử nhân về tâm lý học. Cô tiếp tục diễn xuất trong khi ở trường đại học, tham gia vào sự hồi sinh năm 2001 của The Public Theatre trong vở kịch The Seagull của Anton Chekhov và phần tiếp theo của Star Wars: Episode II - Attack of the Clones (2002). Năm 2004, Portman được đề cử giải Oscar cho Nữ diễn viên phụ xuất sắc nhất và đoạt giải Quả cầu vàng cho vai một vũ nữ thoát y bí ẩn trong phim Closer.
            
            Bộ ba phần tiền truyện của Star Wars kết thúc với Star Wars: Episode III - Revenge of the Sith (2005), sau đó Portman đóng rất nhiều vai diễn. Cô đóng vai Evey Hammond trong phim V for Vendetta (2006), Anne Boleyn trong The Other Boleyn Girl (2008), và một nữ diễn viên ballet trong bộ phim kinh dị tâm lý Black Swan (2010), cô giành giải Oscar cho nữ diễn viên xuất sắc nhất cho vai diễn này. Portman tiếp tục tham gia bộ phim hài lãng mạn No Strings Attached (2011) và có vai Jane Foster trong phim Thor (2011) và Thor: The Dark World (2013). Với vai diễn Jacqueline Kennedy trong bộ phim tiểu sử Jackie (2016), Portman đã nhận được đề cử Oscar thứ ba. Portman là tiếng nói về chính trị của Mỹ và Israel, và là một người ủng hộ quyền động vật và bảo vệ môi trường. Cô kết hôn với vũ công Benjamin Millepied, người mà cô có hai đứa con.', 'image' => 'dv8.jpg'],
            ['name'=> 'Angelina Jolie', 'slug' => Str::slug('Angelina Jolie', '-'), 'birthday'=> '4 tháng 6, 1975 (45 tuổi)', 'nationality' => 'Los Angeles, California, Hoa Kỳ', 'height' => '1m7', 'weight' => '75', 'story' => "Angelina Jolie (/dʒoʊˈliː/; nhũ danh Voight, tên cũ Angelina Jolie Pitt,[1] sinh ngày 4 tháng 6 năm 1975)[2] là một nữ diễn viên, nhà làm phim và nhà nhân đạo người Mỹ. Trong suốt sự nghiệp, cô đã nhận được một giải Oscar và ba giải Quả cầu vàng, cô đã nhiều lần được vinh danh là nữ diễn viên kiếm tiền nhiều nhất Hollywood.

            Jolie xuất hiện lần đầu trên màn ảnh khi còn nhỏ cùng với cha cô, Jon Voight, trong Lookin' to Get Out (1982), và sự nghiệp điện ảnh của cô chính thức bắt đầu một thập kỷ sau đó với Cyborg 2 (1993), tiếp theo là vai chính đầu tiên trong Hackers (1995). Cô đóng vai chính trong các bộ phim được giới phê bình đánh giá cao là George Wallace (1997) và Gia (1998), đồng thời giành Giải Oscar cho nữ diễn viên phụ xuất sắc nhất nhờ diễn xuất trong bộ phim truyền hình Girl, Interrupt năm 1999. Với vai nữ chính của Lara Croft: Tomb Raider (2001) đã giúp cô trở thành nữ diễn viên hàng đầu Hollywood. Cô tiếp tục sự nghiệp ngôi sao hành động của mình với Mr. & Mrs. Smith (2005), Wanted (2008) và Salt (2010), nhận được đánh giá cao của giới phê bình cho màn thể hiện của cô trong các bộ phim truyền hình A Mighty Heart (2007) và Changeling (2008), mang về cho cô một đề cử cho Giải Oscar cho nữ diễn viên chính xuất sắc nhất. Thành công thương mại lớn nhất của cô đến với bộ phim giả tưởng Maleficent (2014). Jolie cũng là đạo diễn và nhà biên kịch cho một số bộ phim truyền hình như In the Land of Blood and Honey (2011), Unbroken (2014) và First They Killed My Father (2017).
            
            Ngoài sự nghiệp điện ảnh, Jolie còn được biết đến với những nỗ lực nhân đạo, cô được trao tặng giải thưởng Nhân đạo Jean Hersholt và Huân chương Saint Michael và Saint George (DCMG), cùng nhiều danh hiệu khác. Cô cũng thúc đẩy các hoạt động bảo tồn, giáo dục và quyền phụ nữ và đã ủng hộ người tị nạn với tư cách là Đặc phái viên của Cao ủy Liên Hiệp Quốc về người tị nạn (UNHCR).
            
            Là người của công chúng, Jolie được coi là một trong những người có ảnh hưởng và quyền lực nhất ngành giải trí Mỹ. Trong nhiều năm, cô được nhiều phương tiện truyền thông bình chọn là người phụ nữ đẹp nhất thế giới. Cuộc sống cá nhân của cô, bao gồm các mối quan hệ, hôn nhân và sức khỏe của cô, là chủ đề của công chúng. Cô đã ly hôn với Jonny Lee Miller và Billy Bob Thornton, và đã ly thân hợp pháp với Brad Pitt; cô và Pitt có với nhau sáu người con, ba trong số đó là con nuôi.", 'image' => 'dv9.jpg'],
            ['name'=> 'Anne Hathaway', 'slug' => Str::slug('Anne Hathaway', '-'), 'birthday'=> 'sinh ngày 12 tháng 11 năm 1982', 'nationality' => 'Mỹ', 'height' => '1m7', 'weight' => '67', 'story' => 'Anne Jacqueline Hathaway chào đời vào ngày 12 tháng 11 năm 1982 tại Brooklyn, New York.7Cô sinh trưởng trong một gia đình có cha - ông Gerald Thomas Hathaway, là một luật sư và mẹ - bà Kathleen Ann "Kate" nhũ danh McCauley, là một nữ diễn viên và cũng là người đã truyền cảm hứng cho Hathaway tiếp bước theo con đường nghiệp diễn của bà.8 Trước đây, bà Kate đã từng đóng vai Phăng-tin trong chuyến lưu diễn vở nhạc kịch Les Misérables "Những người khốn khổ" vòng quanh nước Mỹ lần đầu tiên.9Tròn sáu tuổi, gia đình cô chuyển đến Millburn, New Jersey và đây cũng là nơi cô đã lớn lên.10 Hathaway có một người anh trai - Michael và một người em trai - Thomas, tổ tiên của cô là người Ai-len và Pháp nhưng cô lại mang trong mình dòng máu Đức và thổ dân Mỹ.11 Tên của cô được đặt theo tên vợ của nhà soạn kịch nổi tiếng thế giới - William Shakespeare.

            Thuở thiếu thời, Hathaway là người theo đạo Công giáo La Mã, cô coi việc đó có "giá trị thực sự mạnh mẽ" và cô cũng đã từng bày tỏ ý định muốn trở thành một nữ tu. Nhưng đến năm 15 tuổi, cô quyết định từ bỏ ý nghĩ đó sau khi biết rằng anh trai của cô - Michael là một người đồng tính. Cô nói rằng "Tôi nhận ra anh trai mình là người đồng tính, và tôi không thể ủng hộ một tôn giáo đã không ủng hộ anh tôi. Bây giờ tôi gọi mình là người Cơ Đốc giáo phi giáo phái, bởi vì tôi chưa tìm thấy được tôn giáo dành cho mình". Trong năm 2009, Hathaway nói rằng niềm tin tôn giáo của cô là "một việc đang tiến triển".', 'image' => 'dv10.png'],
        ]);
    }
}
