<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class adddirector extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('director')->insert([
            ['name' => 'Martin Scorsese' , 'slug' => Str::slug('Martin Scorsese', '-'), 'birthday' => '17 tháng 11, 1942 (78 tuổi)',
            'story' => "Martin Scorsese sinh năm 1942 tại thành phố New York trong một gia đình gốc Ý. Bố của Martin là ông Luciano Charles Scorsese (1913–1993) còn mẹ là bà Catherine Scorsese (1912–1997), cả hai đều làm việc ở Garment District của thành phố New York[2]. Ngay từ khi còn nhỏ Martin đã bộc lộ niềm yêu thích với điện ảnh, đặc biệt là với các tác phẩm của Chủ nghĩa hiện thực mới Ý như Kẻ cắp xe đạp (Ladri di biciclette)[3]. Vì niềm yêu thích này Scorsese đã theo học tại Trường Điện ảnh của Đại học New York (NYU phim school), tại đây ông đã giành được bằng cử nhân và thạc sĩ nghệ thuật (Master of Fine Arts) chuyên ngành đạo diễn năm 1966[4]. Trong thời gian học ở trường Martin đã thực hiện một số bộ phim ngắn như What's a Nice Girl Like You Doing in a Place Like This? (1963), It's Not Just You, Murray! (1964) và The Big Shave (1967).",
            'nationality' => 'Thành phố New York, Hoa Kỳ', 'image' => 'dd1.jpg' ],
            ['name' => 'Steven Spielberg', 'slug' => Str::slug('Steven Spielberg', '-'), 'birthday' => '18 tháng 12, 1946 (74 tuổi)', 'story' => "Steven Allan Spielberg KBE (/ˈspiːlbɜːrɡ/; sinh ngày 18 tháng 12 năm 1946) là một đạo diễn, nhà sản xuất kiêm biên kịch phim người Mỹ gốc Do Thái. Ông được coi là một trong những người tiên phong của kỷ nguyên điện ảnh New Hollywood và là một trong những đạo diễn kiêm nhà sản xuất điện ảnh nổi tiếng nhất trong lịch sử.[2] Sau khi có được sự chú ý từ Hollywood với một số các tác phẩm chiếu rạp nhỏ lẻ, Spielberg bắt đầu nổi lên sau khi dự án Hàm cá mập (1975) mà ông đóng vai trò đạo diễn được ra mắt, và giành được thành công lớn về mặt chuyên môn cũng như thương mại, đồng thời mở ra định nghĩa mới về phim bom tấn mùa hè.[3] Các tác phẩm sau đó của ông chủ yếu đi theo thể loại khoa học viễn tưởng như Kiểu tiếp xúc thứ 3 (1977), loạt phim Indiana Jones, E.T. Sinh vật ngoài hành tinh (1982), và loạt phim Công viên kỷ Jura vốn được coi như nguyên mẫu của lối làm phim Hollywood theo trường phái thoát ly.[4]" , 'nationality' => 'Cincinnati, Ohio, Mỹ', 'image' => 'dd2.jpg'],
            ['name' => 'Quentin Tarantino', 'slug' => Str::slug('Quentin Tarantino', '-'), 'birthday' => '27 tháng 3, 1963 (57 tuổi)
            ', 'story' => 'Quentin Jerome Tarantino (/ˌtærənˈtiːnoʊ/; sinh ngày 27 tháng 3 năm 1963)[1] là nhà làm phim và nam diễn viên người Mỹ. Các tác phẩm điện ảnh của ông nổi bật bởi cốt truyện phi tuyến tính, miêu tả nét thẩm mỹ trong yếu tố bạo lực, những phân cảnh đối thoại mở rộng, dàn diễn viên hùng hậu, những mối liên hệ đến văn hóa đại chúng và hàng loạt bộ phim khác, soundtrack chủ yếu chứa các ca khúc và bản nhạc nền từ thập niên 1960 đến thập niên 1980, lịch sử thay thế và mang màu sắc phim đen mới.' , 'nationality' => 'Mỹ', 'image' => 'dd3.jpg'],
            ['name' => 'Christopher Nolan', 'slug' => Str::slug('Christopher Nolan', '-'), 'birthday' => '30 tháng 7, 1970 (50 tuổi)
            ', 'story' => 'Christopher Edward Nolan (/ˈnoʊlən/; sinh ngày 30 tháng 7 năm 1970) là một đạo diễn, nhà biên kịch và nhà sản xuất điện ảnh người Anh. Ông sở hữu cả hai quốc tịch Anh và Mỹ. Nolan là một trong những đạo diễn ăn khách nhất lịch sử, đồng thời là một trong những nhà làm phim được hoan nghênh nhất và có tầm ảnh hưởng lớn nhất của thế kỉ 21.' , 'nationality' => 'Anh Quốc, Hoa Kỳ', 'image' => 'dd4.jpg'],
            ['name' => 'Alfred Hitchcock', 'slug' => Str::slug('Alfred Hitchcock', '-'), 'birthday' => '13 tháng 8 năm 1899', 'story' => 'Alfred Joseph Hichcock sinh ngày 13 tháng 8 năm 1899 ở ngoại ô thành phố London trong một gia đình công giáo. Bố mẹ ông, William và Emma, những người buôn bán nhỏ, có ba người con, William sinh năm 1890, Hichcock và con út Eileen, sinh năm 1892. Những năm tuổi thơ, Hichcock là một đứa trẻ cô đơn và nhút nhát, ông thú nhận ngày bé ông không có nhiều bạn bè và thường chơi đùa một mình. Một vài sự kiện tuổi thơ được tái hiện trong những bộ phim của ông sau này. Alfred Hitchcock rất ghét cảnh sát, điều đó giải thích bởi khi mới 4, 5 tuổi, ông đã phải trải qua một vài ngày trong đồn cảnh sát. Tôn giáo cũng bị chỉ trích trong các phim của ông, Hichcock có những ấn tượng xấu về một trường dòng mà ông đã từng học.' , 'nationality' => 'London, Anh', 'image' => 'dd5.jpg'],
            ['name' => 'Stanley Kubrick', 'slug' => Str::slug('Stanley Kubrick', '-'), 'birthday' => '26 tháng 7, 1928', 'story' => 'Stanley Kubrick sinh ngày 26 tháng 7 năm 1928 tại Bệnh viên Lying-In thuộc khu Manhattan, Thành phố New York. Stanley là con đầu lòng của ông Jacques Leonard Kubrick (1901–1985) và bà Gertrude (1903–1985]]). Năm 1934 Stanley có thêm một người em gái là Barbara.

            Kubrick học phổ thông tại trường William Howard Taft High School từ năm 1941 đến năm 1945.[1] Là một học sinh tồi, Stanley tốt nghiệp năm 1945 với điểm trung bình chỉ là 67/100[2] và không thể hi vọng tiếp tục học cao hơn khi các cựu chiến binh Chiến tranh thế giới thứ hai đang tràn ngập các trường đại học và cao đẳng.
            
            Trong thời gian học phổ thông, Stanley Kubrick được chọn là người chụp ảnh chính thứ của trường và sau khi tốt nghiệp ông quyết định theo đuổi nghề này bằng việc bán ảnh cho tạp chí Look ở thành phố New York. Stanley còn kiếm sống thêm bằng nghề đánh cờ vua ở Công viên Washington Square và những câu lạc bộ cờ ở khu Manhattan.[3] Trong thời gian làm phóng viên ảnh cho tạp chí Look, ngày 29 tháng 5 năm 1948, Kubrick làm đám cưới với Toba Metz (khi đó mới 18 tuổi), hai người sống ở khu Greenwich Village, đến năm 1951 thì họ ly dị.' , 'nationality' => 'Thành phố New York, Hoa Kỳ', 'image' => 'dd6.jpg'],
            ['name' => 'David Fincher', 'slug' => Str::slug('David Fincher', '-'), 'birthday' => '28 tháng 8, 1962 (58 tuổi)
            ', 'story' => "Fincher sinh ngày 28 tháng 8 năm 1962 tại Denver, Colorado (Hoa Kỳ). Mẹ ông là Claire Mae Boettcher, một y tá, còn cha ông là Howard Kelly Fincher, nhân viên văn phòng.[1] Ảnh hưởng từ bộ phim Butch Cassidy and the Sundance Kid, Fincher bắt đầu làm phim từ năm 8 tuổi với máy quay phim 8mm. Từ đó ông theo đuổi sự nghiệp điện ảnh, bắt đầu bằng những công việc tay chân trong hãng John Korty’s Korty Films. Sau đó ông được nhận vào Industrial Light & Magic năm 1983, nơi ông tham gia vào công tác sản xuất trong những phim nổi tiếng như Twice Upon a Time, Star Wars: Episode VI – Return of the Jedi, và Indiana Jones and the Temple of Doom. Năm 1984, ông rời ILM để đạo diễn một quảng cáo của Hội Bệnh nhân ung thư Hoa Kỳ. Ông tiếp tục làm thêm nhiều quảng cáo cho Revlon, Converse, Nike, Pepsi, Sony, và Levi's, sau đó chuyển sang làm video ca nhạc." , 'nationality' => 'Denver, Colorado, Hoa Kỳ.', 'image' => 'dd7.jpg'],
            ['name' => 'Francis Ford Coppola', 'slug' => Str::slug('Francis Ford Coppola', '-'), 'birthday' => '7 tháng 4, 1939 (81 tuổi)
            ', 'story' => 'Ông sinh tại thành phố Detroit tiểu bang Michigan. Bố ông là nghệ sĩ sáo nổi tiếng Carmine Coppola khi đó đang biểu diễn cho Dàn nhạc giao hưởng Detroit, mẹ ông là một phụ nữ Ý và Coppola là con thứ hai trong số 3 người con của nhà Coppola. Hai năm sau Carmine Coppola trở thành nghệ sĩ sáo chính cho Dàn nhạc giao hưởng NBC và cả gia đình chuyển đến Long Island thuộc tiểu bang New York nơi Francis sống phần lớn tuổi thơ của mình. Khi còn nhỏ Coppola bị bại liệt làm cậu thường xuyên phải ngồi yên một chỗ rất lâu, giúp Francis có thời gian thỏa mãn sự tưởng tượng của mình với việc sản xuất một nhà hát của những con rối tự làm. Sử dụng máy quay 8mm của ông Carmine, Francis bắt đầu tập quay phim khi cậu lên 10. Sau đó Coppola vào học ngành sân khấu tại trường Đại học Hofstra trước khi nhận bằng Thạc sĩ nghệ thuật chuyên ngành đạo diễn tại trường điện ảnh của UCLA. Cũng tại đây Francis gặp Jim Morrison, ca sĩ nổi tiếng và là người sáng tác nhạc cho bộ phim Apocalypse Now sau này của ông.' , 'nationality' => 'Mỹ', 'image' => 'dd8.jpg'],
            ['name' => 'Ridley Scott', 'slug' => Str::slug('Ridley Scott', '-'), 'birthday' => '30 tháng 11, 1937 (83 tuổi)
            ', 'story' => "Sir Ridley Scott (sinh 30 tháng 11 năm 1937) là một đạo diễn và nhà sản xuất phim người Anh. Sau bước đột phá thương mại của mình với bộ phim viễn tưởng kinh dị Alien (1979), những tác phẩm nổi tiếng nhất của ông bao gồm bộ phim khoa học viễn tưởng đột phá không tưởng neo-noir Blade Runner (1982), bộ phim lịch sử và đạt giải phim hay nhất Oscar Gladiator (2000) và khoa học viễn tưởng bộ phim The Martian (2015).

            Scott nổi tiếng nghiêm túc, phong cách thị giác tập trung cao.[1][2] Mặc dù các bộ phim của ông có phạm vi trải rộng trong cách sắp đặt và thời kỳ, nhưng thường xuyên giới thiệu những hình ảnh đáng ghi nhớ về môi trường đô thị, cho dù thành Rome thế kỷ 2 (Gladiator), thành Jerusalem thế kỷ 12 (Kingdom of Heaven), Anh thời Trung cổ (Robin Hood), Mogadishu đương đại (Black Hawk Down), những cảnh thành phố trong tương lai của Blade Runner, hoặc các hành tinh xa xôi trong Alien, Prometheus, The Martian và Alien: Covenant. Bộ phim của ông cũng được biết đến với những nhân vật nữ mạnh mẽ.[3] Được giới thiệu vào Science Fiction Hall of Fame năm 2007, vào năm 2017 báo Đức FAZ so sánh ảnh hưởng của Scott đối với thể loại khoa học viễn tưởng cũng như Alfred Hitchcock với thể loại phim kinh dị và John Ford với phim viễn Tây.[4]
            
            Scott đã được đề cử ba giải Oscar cho đạo diễn xuất sắc nhất (cho Thelma & Louise, Gladiator và Black Hawk Down).[1] Năm 1995, cả Ridley và anh trai ông, ông Tony, đều nhận được một BAFTA dành cho đóng góp nổi bật cho Điện ảnh Anh quốc.[5] Năm 2003, Scott được phong tước hiệp sĩ cho 'đóng góp của mình cho ngành công nghiệp điện ảnh Anh'.[6] Trong cuộc bình chọn BBC năm 2004, Scott được mệnh danh là người có ảnh hưởng lớn thứ 10 trong nền văn hoá Anh.[7] Năm 2015, ông nhận bằng tiến sĩ danh dự từ trường Cao đẳng Nghệ thuật Hoàng gia ở London.
            " , 'nationality' => 'South Shields, County Durham, England, UK', 'image' => 'dd9.jpg'],
            ['name' => 'Guillermo del Toro', 'slug' => Str::slug('Guillermo del Toro', '-'), 'birthday' => '9 tháng 10, 1964 (56 tuổi)', 'story' => "Guillermo del Toro Gómez (tiếng Tây Ban Nha: [ɡiˈʝeɾmo ðel ˈtoɾo]; sinh ngày 9 tháng 10 năm 1964) là một đạo diễn phim, biên kịch, nhà sản xuất và tiểu thuyết gia người México. Trong sự nghiệp làm phim của mình, ông đã theo đuổi dòng phim kỳ ảo đen với những tác phẩm tiếng Tây Ban Nha như The Devil's Backbone (2001) và Pan's Labyrinth (2006), đồng thời ông cũng làm nhiều bộ phim hành động Mỹ đại chúng, như phim về siêu anh hùng ma cà rồng Blade II (2002), phim siêu anh hùng siêu nhiên Hellboy (2004) và phần tiếp theo Hellboy II: The Golden Army (2008) và phim khoa học viễn tưởng quái vật Siêu đại chiến (2014).
            Bộ phim kỳ ảo của ông năm 2017 Người đẹp và thủy quái đã nhận được đón nhận phê bình tích cực và giành giải Sư tử vàng tại liên hoan phim quốc tế Venice lần thứ 74 cũng như giải Oscar cho phim hay nhất. Bộ phim cũng giúp del Toro đoạt giải Oscar cho đạo diễn xuất sắc nhất, Quả cầu vàng, giải BAFTA và giải BFCA." , 'nationality' => 'Zapopan, Jalisco, México
            ', 'image' => 'dd10.jpg'],
        ]);
    }
}
